import type { Metadata } from 'next';

type Props = {};

export const metadata: Metadata = {
  title: 'Link Sharing App',
  description: 'Generated by create next app',
};

const Home = (props: Props) => {
  return null;
};

export default Home;
